FROM python:3
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]


# Line #	Status	Explanation
# 1	Same	We want to use the same base image, the python:3 base image
# 2	New	We set an environment variable so that Python prints things immediately
# 3	Same	We set the working directory to /app
# 4	Same	We copy over the requirements.txt so that we can install from it
# 5	Same	We install the dependencies using pip
# 6	Different	We run the Django development server