FROM python:3
RUN apt-get update
RUN apt-get install cron -y
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN touch /var/spool/cron/crontabs/root
RUN crontab -l
CMD python manage.py crontab add && service cron start && python manage.py runserver "0.0.0.0:8001"


# Line #	Status	Explanation
# 1	Same	We want to use the same base image, the python:3 base image
# 2	New	We set an environment variable so that Python prints things immediately
# 3	Same	We set the working directory to /app
# 4	Same	We copy over the requirements.txt so that we can install from it
# 5	Same	We install the dependencies using pip
# 6	Different	We run the Django development server